<form action="/login" method="POST">
    <div class="form-group mb-3">
        <label for="teacher_email" class="form-label">Email</label>
        <input id="teacher_email" type="email" name="teacher[email]" class="form-control" placeholder="Insira o seu e-mail">
    </div>
    <div class="form-group mb-3">
        <label for="teacher_password" class="form-label">Senha</label>
        <input id="teacher_password" type="password" name="teacher[password]" class="form-control" placeholder="Insira a sua senha">
    </div>
    <div class="d-grid">
        <input type="submit" class="btn btn-primary btn-block" value="Entrar">
    </div>
</form>