<div class="row">
   
<div class="col-sm-6">
  <a href="#">
    <div class="card .d-flex flex-row ">
      <div class="card-body d-flex m-1 justify-content-between align-items-center">
        <div class="card-info p-2">
        <h5 class="card-title">Suas Turmas</h5>
        <p class="card-text">1#</p>
        </div>
        <div class="card-icon p-2 justify-content-between">
        <i class="bi bi-person-video3 card-icon"></i>
        </div>
      </div>
    </div>
    </a>
  </div>
    
    
  <div class="col-sm-6">
  <a href="#">
    <div class="card .d-flex flex-row ">
      <div class="card-body d-flex m-1 justify-content-between align-items-center">
        <div class="card-info p-2">
        <h5 class="card-title">Alunos em Turmas</h5>
        <p class="card-text">5#</p>
        </div>
        <div class="card-icon p-2 justify-content-between">
        <i class="bi bi-person-fill card-icon"></i>
        </div>
      </div>
    </div>
    </a>
  </div>
</div>